### ISSUE TITLE
MapSerializer is treating strings as IEnumerable and shouldn't split them in char

### ISSUE THREAD

**Issue by flaviokodama** [flaviokodama/MapSerializer#8]
Since String implements IEnumerable, MapSerializer iterates through it and serializes it separately. 

Example XML: 

            //SETUP
            var instance = new TypeWithEnumerableOfStringProperty() { ListOfStringProperty = new List<string> { "Value 1", "Value 2", "Value 3" } };
            var sampleSerialization = ComparisonSerializer.SerializeToXml(instance);

            this.serializer.MapType<TypeWithEnumerableOfStringProperty>().MapProperty(p => p.ListOfStringProperty);

            //ACTION
            this.serializer.Serialize(writer, new List<string> { "Value 1", "Value 2", "Value 3" });
            var serializedContent = writer.ToString();

            //CHECK
            serializedContent.Should().Be(sampleSerialization);
            
Example JSON:

               //SETUP
            var instance = new TypeWithEnumerableOfStringProperty() { ListOfStringProperty = new List<string> { "Value 1", "Value 2", "Value 3" } };
            var sampleSerialization = ComparisonSerializer.SerializeToJson(instance);

            this.serializer.MapType<TypeWithEnumerableOfStringProperty>().MapProperty(p => p.ListOfStringProperty);

            //ACTION
            this.serializer.Serialize(writer, instance);
            var serializedContent = writer.ToString();

            //CHECK
            serializedContent.Should().Be(sampleSerialization);

**Comment by gustavoferrazfontes** [comment]
I sent a Pull Request to MapSerializer in order to handle with IEnumerable of string and primitive types in general.
